### PR TITLE
Update the tool to use more modern dependencies

### LINKED ISSUE #1: All dependencies are archived and deprecated. Let's upgrade
The `py-cid` dependency is unmaintained https://github.com/ipld/py-cid and archived.

This means that anyone trying to use this repo in a big project will end up hitting constraints due to the version restrictions. For example we at rotki just tried here: https://github.com/rotki/rotki/pull/6259

And we hit this:

```
The conflict is caused by:
    scalecodec 1.2.2 depends on base58>=2.0.1
    substrate-interface 1.6.2 depends on base58<3 and >=1.0.3
    py-cid 0.3.0 depends on base58<2.0 and >=1.0.2
```

Looking here https://github.com/ipld/ipld/issues/251 it seems that the new package to use is: https://github.com/pinnaculum/py-multiformats-cid ?

Would it be possible to update and bump the version?

### PR DESCRIPTION
**Pull request by LefterisJP**
Fix https://github.com/filips123/ContentHashPy/issues/1

As mentioned there, the dependencies were outdated and archived. Since they are no longer maintained, their dependencies are pinned to outdated versions and this causes conflicts when this package is used in more complex projects where transitive dependencies also need the same ones and can't solve the dependency resolution.

The solution is simple. Update to more modern packages.

After looking around a bit it seems that the proper package to use here is https://github.com/hashberg-io/multiformats
It contains everything needed for the content hash EIP, plus I added some more dependencies to do small stuff like base58 encode/decode and use keccak.

Have a small constraint I added temporarily due to https://github.com/hashberg-io/multiformats/issues/10 but this can be removed soon.

I checked that all tests pass with the changes, so I am at least sure that the functionality is the same. Only thing I had to change was the `-ns` suffix for some protocols as this is not understood/supported in multiformats package.

Since we want to use this in production in rotki: https://github.com/rotki/rotki/ and I am not sure if this repo is still maintained I went ahead and made a fork and [uploaded it to pypi](https://pypi.org/project/rotki-content-hash/) with those changes in this PR so we and others can use it easily.

But if the changes make it into the upstream we can just keep using this package and retire the fork.

### CODE REVIEW

**Comment by filips123** [comment]
Thanks! I'll review this PR next week as I don't have much time at the moment.

**Comment by filips123** [comment]
I've noticed that `pysha3` is also no longer supported because SHA3 is now (since Python 3.6) available in standard library's `hashlib`. Can you please switch to that and also increase minimum Python version to 3.7 in `setup.py` (because 3.7 is also required by `multiformats`)?

**Comment by filips123** [comment]
Also, I've replaced Travis CI with GitHub Actions, so please update your branch so tests become available.

**Comment by LefterisJP** [comment]
Hey I am just writing to say these days are really busy but will get to it at some point! Have not forgotten it

**Comment by sg495** [comment]
Heya.

Just wanted to say that issue https://github.com/hashberg-io/multiformats/issues/10 is now closed, along with all other outstanding issues, and that [`multiformats`](https://github.com/hashberg-io/multiformats) is going to be regularly maintained. Following pull request https://github.com/hashberg-io/multiformats/pull/16 and starting from version [`multiformats>=0.3.1.post4`](https://pypi.org/project/multiformats/0.3.1.post4), the `pysha3` dependency for keccak has been dropped in favour of `pycryptodomex`.

If you need help in your codebase transition to `multiformats`, feel free to give me a shout. Always happy to integrate new functionality.

**Pull request closed without merging**
