### PR TITLE
Upgrade dependencies

### LINKED ISSUE #1: All dependencies are archived and deprecated. Let's upgrade
The `py-cid` dependency is unmaintained https://github.com/ipld/py-cid and archived.

This means that anyone trying to use this repo in a big project will end up hitting constraints due to the version restrictions. For example we at rotki just tried here: https://github.com/rotki/rotki/pull/6259

And we hit this:

```
The conflict is caused by:
    scalecodec 1.2.2 depends on base58>=2.0.1
    substrate-interface 1.6.2 depends on base58<3 and >=1.0.3
    py-cid 0.3.0 depends on base58<2.0 and >=1.0.2
```

Looking here https://github.com/ipld/ipld/issues/251 it seems that the new package to use is: https://github.com/pinnaculum/py-multiformats-cid ?

Would it be possible to update and bump the version?

### PR DESCRIPTION
**Pull request by yabirgb**
Hello! I'm yabir from the @rotki team and I work with @lefterisjp. Recently there was a release and it broke our app as we were running a fork of this project. What I've done here is:

- update the dependencies
- replace the setup.py with pyproject.toml
- adjusted types in the functions

The only issue is that I had to make a PR to add support for keccak at https://github.com/hashberg-io/multiformats/pull/16 and it hasn't release yet.

Feel free to review and once it releases my patch we can update the dep in the pyproject

### CODE REVIEW

**Comment by sg495** [comment]
Hi everybody, and apologies for the temporary drop in keccak support. Following @yabirgb's [pull request](https://github.com/hashberg-io/multiformats/pull/16), we have now released [`multiformats>=0.3.1.post4`](https://pypi.org/project/multiformats/0.3.1.post4), with keccak support restored (now based on `pycryptodomex`).

**Comment by yabirgb** [comment]
@filips123 feel free to check when you can

**Comment by filips123** [comment]
Does this PR replace #2?

**Comment by yabirgb** [comment]
Yes @filips123 ! It finishes what was started in #2

**Review by filips123 — APPROVED** [review]
Thanks, it seems fine. I will probably make a few other changes and then release it soon.

**Pull request merged**
